### ISSUE TITLE
Please change bugtracker link

### ISSUE THREAD

**Issue by pcav** [ODTBuilder/OpenGDS-Desktop-QgisPlugin#4]
It currently points to the repo, not to the issues page.
Thanks.

**Comment by pcav** [comment]
@OpenGeoDT could you please fix these issues so that I can publish your plugin?

**Comment by SOYIJUN** [comment]
> @OpenGeoDT could you please fix these issues so that I can publish your plugin?
I am sorry for the waiting. if you mean the link in the file "GeoDT/metadata.txt", it has been fixed. 
Thank you for your feedback.

**Comment by pcav** [comment]
Please check https://plugins.qgis.org/plugins/GeoDT/ also the web interface should be updated

**Comment by SOYIJUN** [comment]
> Please check https://plugins.qgis.org/plugins/GeoDT/ also the web interface should be updated

Now it fixed also. thanks!

**Comment by pcav** [comment]
Fine, tahnks.
